name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./dist

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run security check
        run: npm audit

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

  static-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run static analysis
        run: npm run analyze

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - static-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist

      - name: Set deployment URL
        id: set-url
        run: echo "::set-output name=page_url::https://AndreaQuin12.github.io/CICD_AndreaQuin/"

  verify-job:
    name: Verify Deployment
    needs: deploy
    runs-on: ubuntu-latest
    if: success()
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run smoke test
        run: |
          export TEST_URL=${{needs.deploy.outputs.page_url}}
          cd tests
          npm install
          npm run smoke
